function G = Gravity(in1,g)
%GRAVITY
%    G = GRAVITY(IN1,G)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    11-Apr-2019 15:17:26

th2 = in1(:,2);
th3 = in1(:,3);
t2 = conj(th2);
t3 = conj(th3);
t4 = t2+t3;
t5 = sin(t4);
G = [0.0;-g.*(t5.*(1.0./1.0e1)+sin(t2+t3-th3).*(3.0./1.0e1)+sin(t2).*(1.0./4.0));g.*t5.*(-1.0./1.0e1)];
