function M = PM3(in)
%PM3
%    M = PM3(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    02-Apr-2019 17:51:17

q2 = in(2);
q3 = in(3);
t2 = q2.*2.0;
t3 = cos(q3);
t4 = t3.*(3.0./1.0e2);
t5 = t4+1.15e-2;
M = reshape([t4-cos(q3.*2.0+t2)./2.0e2-cos(q3+t2).*(3.0./1.0e2)-cos(t2).*(7.0./1.0e2)+8.22e-2,0.0,0.0,0.0,t3.*(3.0./5.0e1)+1.537e-1,t5,0.0,t5,1.15e-2],[3,3]);
