function V = Velocity(in)
%VELOCITY
%    V = VELOCITY(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    06-Apr-2019 17:58:05

th2 = in(2);
th3 = in(3);
thdot1 = in(4);
thdot2 = in(5);
thdot3 = in(6);
t2 = conj(th2);
t3 = th2-1.570796326794897;
t4 = cos(t3);
t5 = cos(t2);
t6 = conj(th3);
t7 = t6-1.570796326794897;
t8 = sin(t2);
t9 = cos(t7);
t10 = sin(t7);
t11 = sin(t3);
t12 = thdot1.^2;
t13 = t2.*2.0;
t14 = t13-3.141592653589793;
t15 = sin(t14);
t16 = t12.*t15.*2.5e-2;
t17 = t4.*t5.*thdot1.*thdot2.*3.0e-2;
t18 = t4.*t8.*thdot1.*thdot2.*-4.326295539405825e-35;
t19 = t4.*t5.*t10.*thdot1.*thdot2.*-2.15e-2;
t20 = t5.*t9.*t11.*thdot1.*thdot2.*1.5e-3;
t21 = t4.*t8.*t9.*thdot1.*thdot2.*-2.15e-2;
t22 = t4.*t5.*t10.*thdot1.*thdot3.*-2.15e-2;
t23 = t5.*t9.*t11.*thdot1.*thdot3.*1.5e-3;
t24 = t4.*t8.*t9.*thdot1.*thdot3.*-2.15e-2;
t25 = t8.*t10.*t11.*thdot1.*thdot2.*-1.5e-3;
t26 = t8.*t10.*t11.*thdot1.*thdot3.*-1.5e-3;
t27 = t16+t17+t18+t19+t20+t21+t22+t23+t24+t25+t26;
t28 = t2.*2.0;
t29 = thdot2.^2;
V = [t27;t27;t12.*sin(t6.*2.0+t28-3.141592653589793).*5.0e-3+t12.*t29.*sin(t6).*1.5e-2-t12.*t29.*sin(t6+t28-3.141592653589793).*1.5e-2];
