using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace MangoConversions.Conversion
{
    public static class Prefixes
    {
        //Prefix definitions acquired here https://physics.nist.gov/cuu/Units/prefixes.html

        #region Prefix Dictionary

        //KEYS: prefix name
        //VALUES: prefix value
        private static readonly ReadOnlyDictionary<string, double> _prefs = BuildDictionary();
        private static ReadOnlyDictionary<string, double> BuildDictionary()
        {
            Dictionary<string, double> dict = new Dictionary<string, double>
            {
                //yotta conversions
			    {"YottaToYotta", 1.00E+00},
                {"YottaToZetta", 1.00E+03},
                {"YottaToExa", 1.00E+06},
                {"YottaToPeta", 1.00E+09},
                {"YottaToTera", 1.00E+12},
                {"YottaToGiga", 1.00E+15},
                {"YottaToMega", 1.00E+18},
                {"YottaToKilo", 1.00E+21},
                {"YottaToHecto", 1.00E+22},
                {"YottaToDeka", 1.00E+23},
                {"YottaToDeci", 1.00E+25},
                {"YottaToCenti", 1.00E+26},
                {"YottaToMilli", 1.00E+27},
                {"YottaToMicro", 1.00E+30},
                {"YottaToNano", 1.00E+33},
                {"YottaToPico", 1.00E+36},
                {"YottaToFemto", 1.00E+39},
                {"YottaToAtto", 1.00E+42},
                {"YottaToZepto", 1.00E+45},
                {"YottaToYocto", 1.00E+48},

                //zetta conversions
                {"ZettaToYotta", 1.00E-03},
                {"ZettaToZetta", 1.00E+00},
                {"ZettaToExa", 1.00E+03},
                {"ZettaToPeta", 1.00E+06},
                {"ZettaToTera", 1.00E+09},
                {"ZettaToGiga", 1.00E+12},
                {"ZettaToMega", 1.00E+15},
                {"ZettaToKilo", 1.00E+18},
                {"ZettaToHecto", 1.00E+19},
                {"ZettaToDeka", 1.00E+20},
                {"ZettaToDeci", 1.00E+22},
                {"ZettaToCenti", 1.00E+23},
                {"ZettaToMilli", 1.00E+24},
                {"ZettaToMicro", 1.00E+27},
                {"ZettaToNano", 1.00E+30},
                {"ZettaToPico", 1.00E+33},
                {"ZettaToFemto", 1.00E+36},
                {"ZettaToAtto", 1.00E+39},
                {"ZettaToZepto", 1.00E+42},
                {"ZettaToYocto", 1.00E+45},

                //exa conversions
                {"ExaToYotta", 1.00E-06},
                {"ExaToZetta", 1.00E-03},
                {"ExaToExa", 1.00E+00},
                {"ExaToPeta", 1.00E+03},
                {"ExaToTera", 1.00E+06},
                {"ExaToGiga", 1.00E+09},
                {"ExaToMega", 1.00E+12},
                {"ExaToKilo", 1.00E+15},
                {"ExaToHecto", 1.00E+16},
                {"ExaToDeka", 1.00E+17},
                {"ExaToDeci", 1.00E+19},
                {"ExaToCenti", 1.00E+20},
                {"ExaToMilli", 1.00E+21},
                {"ExaToMicro", 1.00E+24},
                {"ExaToNano", 1.00E+27},
                {"ExaToPico", 1.00E+30},
                {"ExaToFemto", 1.00E+33},
                {"ExaToAtto", 1.00E+36},
                {"ExaToZepto", 1.00E+39},
                {"ExaToYocto", 1.00E+42},

                //peta conversions
                {"PetaToYotta", 1.00E-09},
                {"PetaToZetta", 1.00E-06},
                {"PetaToExa", 1.00E-03},
                {"PetaToPeta", 1.00E+00},
                {"PetaToTera", 1.00E+03},
                {"PetaToGiga", 1.00E+06},
                {"PetaToMega", 1.00E+09},
                {"PetaToKilo", 1.00E+12},
                {"PetaToHecto", 1.00E+13},
                {"PetaToDeka", 1.00E+14},
                {"PetaToDeci", 1.00E+16},
                {"PetaToCenti", 1.00E+17},
                {"PetaToMilli", 1.00E+18},
                {"PetaToMicro", 1.00E+21},
                {"PetaToNano", 1.00E+24},
                {"PetaToPico", 1.00E+27},
                {"PetaToFemto", 1.00E+30},
                {"PetaToAtto", 1.00E+33},
                {"PetaToZepto", 1.00E+36},
                {"PetaToYocto", 1.00E+39},

                //tera conversions
                {"TeraToYotta", 1.00E-12},
                {"TeraToZetta", 1.00E-09},
                {"TeraToExa", 1.00E-06},
                {"TeraToPeta", 1.00E-03},
                {"TeraToTera", 1.00E+00},
                {"TeraToGiga", 1.00E+03},
                {"TeraToMega", 1.00E+06},
                {"TeraToKilo", 1.00E+09},
                {"TeraToHecto", 1.00E+10},
                {"TeraToDeka", 1.00E+11},
                {"TeraToDeci", 1.00E+13},
                {"TeraToCenti", 1.00E+14},
                {"TeraToMilli", 1.00E+15},
                {"TeraToMicro", 1.00E+18},
                {"TeraToNano", 1.00E+21},
                {"TeraToPico", 1.00E+24},
                {"TeraToFemto", 1.00E+27},
                {"TeraToAtto", 1.00E+30},
                {"TeraToZepto", 1.00E+33},
                {"TeraToYocto", 1.00E+36},

                //giga conversions
                {"GigaToYotta", 1.00E-15},
                {"GigaToZetta", 1.00E-12},
                {"GigaToExa", 1.00E-09},
                {"GigaToPeta", 1.00E-06},
                {"GigaToTera", 1.00E-03},
                {"GigaToGiga", 1.00E+00},
                {"GigaToMega", 1.00E+03},
                {"GigaToKilo", 1.00E+06},
                {"GigaToHecto", 1.00E+07},
                {"GigaToDeka", 1.00E+08},
                {"GigaToDeci", 1.00E+10},
                {"GigaToCenti", 1.00E+11},
                {"GigaToMilli", 1.00E+12},
                {"GigaToMicro", 1.00E+15},
                {"GigaToNano", 1.00E+18},
                {"GigaToPico", 1.00E+21},
                {"GigaToFemto", 1.00E+24},
                {"GigaToAtto", 1.00E+27},
                {"GigaToZepto", 1.00E+30},
                {"GigaToYocto", 1.00E+33},

                //mega conversions
                {"MegaToYotta", 1.00E-18},
                {"MegaToZetta", 1.00E-15},
                {"MegaToExa", 1.00E-12},
                {"MegaToPeta", 1.00E-09},
                {"MegaToTera", 1.00E-06},
                {"MegaToGiga", 1.00E-03},
                {"MegaToMega", 1.00E+00},
                {"MegaToKilo", 1.00E+03},
                {"MegaToHecto", 1.00E+04},
                {"MegaToDeka", 1.00E+05},
                {"MegaToDeci", 1.00E+07},
                {"MegaToCenti", 1.00E+08},
                {"MegaToMilli", 1.00E+09},
                {"MegaToMicro", 1.00E+12},
                {"MegaToNano", 1.00E+15},
                {"MegaToPico", 1.00E+18},
                {"MegaToFemto", 1.00E+21},
                {"MegaToAtto", 1.00E+24},
                {"MegaToZepto", 1.00E+27},
                {"MegaToYocto", 1.00E+30},

                //kilo conversions
                {"KiloToYotta", 1.00E-21},
                {"KiloToZetta", 1.00E-18},
                {"KiloToExa", 1.00E-15},
                {"KiloToPeta", 1.00E-12},
                {"KiloToTera", 1.00E-09},
                {"KiloToGiga", 1.00E-06},
                {"KiloToMega", 1.00E-03},
                {"KiloToKilo", 1.00E+00},
                {"KiloToHecto", 1.00E+01},
                {"KiloToDeka", 1.00E+02},
                {"KiloToDeci", 1.00E+04},
                {"KiloToCenti", 1.00E+05},
                {"KiloToMilli", 1.00E+06},
                {"KiloToMicro", 1.00E+09},
                {"KiloToNano", 1.00E+12},
                {"KiloToPico", 1.00E+15},
                {"KiloToFemto", 1.00E+18},
                {"KiloToAtto", 1.00E+21},
                {"KiloToZepto", 1.00E+24},
                {"KiloToYocto", 1.00E+27},

                //hecto conversions
                {"HectoToYotta", 1.00E-22},
                {"HectoToZetta", 1.00E-19},
                {"HectoToExa", 1.00E-16},
                {"HectoToPeta", 1.00E-13},
                {"HectoToTera", 1.00E-10},
                {"HectoToGiga", 1.00E-07},
                {"HectoToMega", 1.00E-04},
                {"HectoToKilo", 1.00E-01},
                {"HectoToHecto", 1.00E+00},
                {"HectoToDeka", 1.00E+01},
                {"HectoToDeci", 1.00E+03},
                {"HectoToCenti", 1.00E+04},
                {"HectoToMilli", 1.00E+05},
                {"HectoToMicro", 1.00E+08},
                {"HectoToNano", 1.00E+11},
                {"HectoToPico", 1.00E+14},
                {"HectoToFemto", 1.00E+17},
                {"HectoToAtto", 1.00E+20},
                {"HectoToZepto", 1.00E+23},
                {"HectoToYocto", 1.00E+26},

                //deka conversions
                {"DekaToYotta", 1.00E-23},
                {"DekaToZetta", 1.00E-20},
                {"DekaToExa", 1.00E-17},
                {"DekaToPeta", 1.00E-14},
                {"DekaToTera", 1.00E-11},
                {"DekaToGiga", 1.00E-08},
                {"DekaToMega", 1.00E-05},
                {"DekaToKilo", 1.00E-02},
                {"DekaToHecto", 1.00E-01},
                {"DekaToDeka", 1.00E+00},
                {"DekaToDeci", 1.00E+02},
                {"DekaToCenti", 1.00E+03},
                {"DekaToMilli", 1.00E+04},
                {"DekaToMicro", 1.00E+07},
                {"DekaToNano", 1.00E+10},
                {"DekaToPico", 1.00E+13},
                {"DekaToFemto", 1.00E+16},
                {"DekaToAtto", 1.00E+19},
                {"DekaToZepto", 1.00E+22},
                {"DekaToYocto", 1.00E+25},

                //deci conversions
                {"DeciToYotta", 1.00E-25},
                {"DeciToZetta", 1.00E-22},
                {"DeciToExa", 1.00E-19},
                {"DeciToPeta", 1.00E-16},
                {"DeciToTera", 1.00E-13},
                {"DeciToGiga", 1.00E-10},
                {"DeciToMega", 1.00E-07},
                {"DeciToKilo", 1.00E-04},
                {"DeciToHecto", 1.00E-03},
                {"DeciToDeka", 1.00E-02},
                {"DeciToDeci", 1.00E+00},
                {"DeciToCenti", 1.00E+01},
                {"DeciToMilli", 1.00E+02},
                {"DeciToMicro", 1.00E+05},
                {"DeciToNano", 1.00E+08},
                {"DeciToPico", 1.00E+11},
                {"DeciToFemto", 1.00E+14},
                {"DeciToAtto", 1.00E+17},
                {"DeciToZepto", 1.00E+20},
                {"DeciToYocto", 1.00E+23},

                //centi conversions
                {"CentiToYotta", 1.00E-26},
                {"CentiToZetta", 1.00E-23},
                {"CentiToExa", 1.00E-20},
                {"CentiToPeta", 1.00E-17},
                {"CentiToTera", 1.00E-14},
                {"CentiToGiga", 1.00E-11},
                {"CentiToMega", 1.00E-08},
                {"CentiToKilo", 1.00E-05},
                {"CentiToHecto", 1.00E-04},
                {"CentiToDeka", 1.00E-03},
                {"CentiToDeci", 1.00E-01},
                {"CentiToCenti", 1.00E+00},
                {"CentiToMilli", 1.00E+01},
                {"CentiToMicro", 1.00E+04},
                {"CentiToNano", 1.00E+07},
                {"CentiToPico", 1.00E+10},
                {"CentiToFemto", 1.00E+13},
                {"CentiToAtto", 1.00E+16},
                {"CentiToZepto", 1.00E+19},
                {"CentiToYocto", 1.00E+22},

                //milli conversions
                {"MilliToYotta", 1.00E-27},
                {"MilliToZetta", 1.00E-24},
                {"MilliToExa", 1.00E-21},
                {"MilliToPeta", 1.00E-18},
                {"MilliToTera", 1.00E-15},
                {"MilliToGiga", 1.00E-12},
                {"MilliToMega", 1.00E-09},
                {"MilliToKilo", 1.00E-06},
                {"MilliToHecto", 1.00E-05},
                {"MilliToDeka", 1.00E-04},
                {"MilliToDeci", 1.00E-02},
                {"MilliToCenti", 1.00E-01},
                {"MilliToMilli", 1.00E+00},
                {"MilliToMicro", 1.00E+03},
                {"MilliToNano", 1.00E+06},
                {"MilliToPico", 1.00E+09},
                {"MilliToFemto", 1.00E+12},
                {"MilliToAtto", 1.00E+15},
                {"MilliToZepto", 1.00E+18},
                {"MilliToYocto", 1.00E+21},

                //micro conversions
                {"MicroToYotta", 1.00E-30},
                {"MicroToZetta", 1.00E-27},
                {"MicroToExa", 1.00E-24},
                {"MicroToPeta", 1.00E-21},
                {"MicroToTera", 1.00E-18},
                {"MicroToGiga", 1.00E-15},
                {"MicroToMega", 1.00E-12},
                {"MicroToKilo", 1.00E-09},
                {"MicroToHecto", 1.00E-08},
                {"MicroToDeka", 1.00E-07},
                {"MicroToDeci", 1.00E-05},
                {"MicroToCenti", 1.00E-04},
                {"MicroToMilli", 1.00E-03},
                {"MicroToMicro", 1.00E+00},
                {"MicroToNano", 1.00E+03},
                {"MicroToPico", 1.00E+06},
                {"MicroToFemto", 1.00E+09},
                {"MicroToAtto", 1.00E+12},
                {"MicroToZepto", 1.00E+15},
                {"MicroToYocto", 1.00E+18},

                //nano conversions
                {"NanoToYotta", 1.00E-33},
                {"NanoToZetta", 1.00E-30},
                {"NanoToExa", 1.00E-27},
                {"NanoToPeta", 1.00E-24},
                {"NanoToTera", 1.00E-21},
                {"NanoToGiga", 1.00E-18},
                {"NanoToMega", 1.00E-15},
                {"NanoToKilo", 1.00E-12},
                {"NanoToHecto", 1.00E-11},
                {"NanoToDeka", 1.00E-10},
                {"NanoToDeci", 1.00E-08},
                {"NanoToCenti", 1.00E-07},
                {"NanoToMilli", 1.00E-06},
                {"NanoToMicro", 1.00E-03},
                {"NanoToNano", 1.00E+00},
                {"NanoToPico", 1.00E+03},
                {"NanoToFemto", 1.00E+06},
                {"NanoToAtto", 1.00E+09},
                {"NanoToZepto", 1.00E+12},
                {"NanoToYocto", 1.00E+15},

                //pico conversions
                {"PicoToYotta", 1.00E-36},
                {"PicoToZetta", 1.00E-33},
                {"PicoToExa", 1.00E-30},
                {"PicoToPeta", 1.00E-27},
                {"PicoToTera", 1.00E-24},
                {"PicoToGiga", 1.00E-21},
                {"PicoToMega", 1.00E-18},
                {"PicoToKilo", 1.00E-15},
                {"PicoToHecto", 1.00E-14},
                {"PicoToDeka", 1.00E-13},
                {"PicoToDeci", 1.00E-11},
                {"PicoToCenti", 1.00E-10},
                {"PicoToMilli", 1.00E-09},
                {"PicoToMicro", 1.00E-06},
                {"PicoToNano", 1.00E-03},
                {"PicoToPico", 1.00E+00},
                {"PicoToFemto", 1.00E+03},
                {"PicoToAtto", 1.00E+06},
                {"PicoToZepto", 1.00E+09},
                {"PicoToYocto", 1.00E+12},

                //femto conversions
                {"FemtoToYotta", 1.00E-39},
                {"FemtoToZetta", 1.00E-36},
                {"FemtoToExa", 1.00E-33},
                {"FemtoToPeta", 1.00E-30},
                {"FemtoToTera", 1.00E-27},
                {"FemtoToGiga", 1.00E-24},
                {"FemtoToMega", 1.00E-21},
                {"FemtoToKilo", 1.00E-18},
                {"FemtoToHecto", 1.00E-17},
                {"FemtoToDeka", 1.00E-16},
                {"FemtoToDeci", 1.00E-14},
                {"FemtoToCenti", 1.00E-13},
                {"FemtoToMilli", 1.00E-12},
                {"FemtoToMicro", 1.00E-09},
                {"FemtoToNano", 1.00E-06},
                {"FemtoToPico", 1.00E-03},
                {"FemtoToFemto", 1.00E+00},
                {"FemtoToAtto", 1.00E+03},
                {"FemtoToZepto", 1.00E+06},
                {"FemtoToYocto", 1.00E+09},

                //atto conversions
                {"AttoToYotta", 1.00E-42},
                {"AttoToZetta", 1.00E-39},
                {"AttoToExa", 1.00E-36},
                {"AttoToPeta", 1.00E-33},
                {"AttoToTera", 1.00E-30},
                {"AttoToGiga", 1.00E-27},
                {"AttoToMega", 1.00E-24},
                {"AttoToKilo", 1.00E-21},
                {"AttoToHecto", 1.00E-20},
                {"AttoToDeka", 1.00E-19},
                {"AttoToDeci", 1.00E-17},
                {"AttoToCenti", 1.00E-16},
                {"AttoToMilli", 1.00E-15},
                {"AttoToMicro", 1.00E-12},
                {"AttoToNano", 1.00E-09},
                {"AttoToPico", 1.00E-06},
                {"AttoToFemto", 1.00E-03},
                {"AttoToAtto", 1.00E+00},
                {"AttoToZepto", 1.00E+03},
                {"AttoToYocto", 1.00E+06},

                //zepto conversions
                {"ZeptoToYotta", 1.00E-45},
                {"ZeptoToZetta", 1.00E-42},
                {"ZeptoToExa", 1.00E-39},
                {"ZeptoToPeta", 1.00E-36},
                {"ZeptoToTera", 1.00E-33},
                {"ZeptoToGiga", 1.00E-30},
                {"ZeptoToMega", 1.00E-27},
                {"ZeptoToKilo", 1.00E-24},
                {"ZeptoToHecto", 1.00E-23},
                {"ZeptoToDeka", 1.00E-22},
                {"ZeptoToDeci", 1.00E-20},
                {"ZeptoToCenti", 1.00E-19},
                {"ZeptoToMilli", 1.00E-18},
                {"ZeptoToMicro", 1.00E-15},
                {"ZeptoToNano", 1.00E-12},
                {"ZeptoToPico", 1.00E-09},
                {"ZeptoToFemto", 1.00E-06},
                {"ZeptoToAtto", 1.00E-03},
                {"ZeptoToZepto", 1.00E+00},
                {"ZeptoToYocto", 1.00E+03},

                //yocto conversions
                {"YoctoToYotta", 1.00E-48},
                {"YoctoToZetta", 1.00E-45},
                {"YoctoToExa", 1.00E-42},
                {"YoctoToPeta", 1.00E-39},
                {"YoctoToTera", 1.00E-36},
                {"YoctoToGiga", 1.00E-33},
                {"YoctoToMega", 1.00E-30},
                {"YoctoToKilo", 1.00E-27},
                {"YoctoToHecto", 1.00E-26},
                {"YoctoToDeka", 1.00E-25},
                {"YoctoToDeci", 1.00E-23},
                {"YoctoToCenti", 1.00E-22},
                {"YoctoToMilli", 1.00E-21},
                {"YoctoToMicro", 1.00E-18},
                {"YoctoToNano", 1.00E-15},
                {"YoctoToPico", 1.00E-12},
                {"YoctoToFemto", 1.00E-09},
                {"YoctoToAtto", 1.00E-06},
                {"YoctoToZepto", 1.00E-03},
                {"YoctoToYocto", 1.00E+00}
            };

            return new ReadOnlyDictionary<string, double>(dict);
        }
        public enum PrefixConversion
        {
            //yotta enums
            YottaToYotta,
            YottaToZetta,
            YottaToExa,
            YottaToPeta,
            YottaToTera,
            YottaToGiga,
            YottaToMega,
            YottaToKilo,
            YottaToHecto,
            YottaToDeka,
            YottaToDeci,
            YottaToCenti,
            YottaToMilli,
            YottaToMicro,
            YottaToNano,
            YottaToPico,
            YottaToFemto,
            YottaToAtto,
            YottaToZepto,
            YottaToYocto,

            //zetta enums
            ZettaToYotta,
            ZettaToZetta,
            ZettaToExa,
            ZettaToPeta,
            ZettaToTera,
            ZettaToGiga,
            ZettaToMega,
            ZettaToKilo,
            ZettaToHecto,
            ZettaToDeka,
            ZettaToDeci,
            ZettaToCenti,
            ZettaToMilli,
            ZettaToMicro,
            ZettaToNano,
            ZettaToPico,
            ZettaToFemto,
            ZettaToAtto,
            ZettaToZepto,
            ZettaToYocto,

            //exa enums
            ExaToYotta,
            ExaToZetta,
            ExaToExa,
            ExaToPeta,
            ExaToTera,
            ExaToGiga,
            ExaToMega,
            ExaToKilo,
            ExaToHecto,
            ExaToDeka,
            ExaToDeci,
            ExaToCenti,
            ExaToMilli,
            ExaToMicro,
            ExaToNano,
            ExaToPico,
            ExaToFemto,
            ExaToAtto,
            ExaToZepto,
            ExaToYocto,

            //peta enums
            PetaToYotta,
            PetaToZetta,
            PetaToExa,
            PetaToPeta,
            PetaToTera,
            PetaToGiga,
            PetaToMega,
            PetaToKilo,
            PetaToHecto,
            PetaToDeka,
            PetaToDeci,
            PetaToCenti,
            PetaToMilli,
            PetaToMicro,
            PetaToNano,
            PetaToPico,
            PetaToFemto,
            PetaToAtto,
            PetaToZepto,
            PetaToYocto,

            //tera enums
            TeraToYotta,
            TeraToZetta,
            TeraToExa,
            TeraToPeta,
            TeraToTera,
            TeraToGiga,
            TeraToMega,
            TeraToKilo,
            TeraToHecto,
            TeraToDeka,
            TeraToDeci,
            TeraToCenti,
            TeraToMilli,
            TeraToMicro,
            TeraToNano,
            TeraToPico,
            TeraToFemto,
            TeraToAtto,
            TeraToZepto,
            TeraToYocto,

            //giga enums
            GigaToYotta,
            GigaToZetta,
            GigaToExa,
            GigaToPeta,
            GigaToTera,
            GigaToGiga,
            GigaToMega,
            GigaToKilo,
            GigaToHecto,
            GigaToDeka,
            GigaToDeci,
            GigaToCenti,
            GigaToMilli,
            GigaToMicro,
            GigaToNano,
            GigaToPico,
            GigaToFemto,
            GigaToAtto,
            GigaToZepto,
            GigaToYocto,

            //mega enums
            MegaToYotta,
            MegaToZetta,
            MegaToExa,
            MegaToPeta,
            MegaToTera,
            MegaToGiga,
            MegaToMega,
            MegaToKilo,
            MegaToHecto,
            MegaToDeka,
            MegaToDeci,
            MegaToCenti,
            MegaToMilli,
            MegaToMicro,
            MegaToNano,
            MegaToPico,
            MegaToFemto,
            MegaToAtto,
            MegaToZepto,
            MegaToYocto,

            //kilo enums
            KiloToYotta,
            KiloToZetta,
            KiloToExa,
            KiloToPeta,
            KiloToTera,
            KiloToGiga,
            KiloToMega,
            KiloToKilo,
            KiloToHecto,
            KiloToDeka,
            KiloToDeci,
            KiloToCenti,
            KiloToMilli,
            KiloToMicro,
            KiloToNano,
            KiloToPico,
            KiloToFemto,
            KiloToAtto,
            KiloToZepto,
            KiloToYocto,

            //hecto enums
            HectoToYotta,
            HectoToZetta,
            HectoToExa,
            HectoToPeta,
            HectoToTera,
            HectoToGiga,
            HectoToMega,
            HectoToKilo,
            HectoToHecto,
            HectoToDeka,
            HectoToDeci,
            HectoToCenti,
            HectoToMilli,
            HectoToMicro,
            HectoToNano,
            HectoToPico,
            HectoToFemto,
            HectoToAtto,
            HectoToZepto,
            HectoToYocto,

            //deka enums
            DekaToYotta,
            DekaToZetta,
            DekaToExa,
            DekaToPeta,
            DekaToTera,
            DekaToGiga,
            DekaToMega,
            DekaToKilo,
            DekaToHecto,
            DekaToDeka,
            DekaToDeci,
            DekaToCenti,
            DekaToMilli,
            DekaToMicro,
            DekaToNano,
            DekaToPico,
            DekaToFemto,
            DekaToAtto,
            DekaToZepto,
            DekaToYocto,

            //deci enums
            DeciToYotta,
            DeciToZetta,
            DeciToExa,
            DeciToPeta,
            DeciToTera,
            DeciToGiga,
            DeciToMega,
            DeciToKilo,
            DeciToHecto,
            DeciToDeka,
            DeciToDeci,
            DeciToCenti,
            DeciToMilli,
            DeciToMicro,
            DeciToNano,
            DeciToPico,
            DeciToFemto,
            DeciToAtto,
            DeciToZepto,
            DeciToYocto,

            //centi enums
            CentiToYotta,
            CentiToZetta,
            CentiToExa,
            CentiToPeta,
            CentiToTera,
            CentiToGiga,
            CentiToMega,
            CentiToKilo,
            CentiToHecto,
            CentiToDeka,
            CentiToDeci,
            CentiToCenti,
            CentiToMilli,
            CentiToMicro,
            CentiToNano,
            CentiToPico,
            CentiToFemto,
            CentiToAtto,
            CentiToZepto,
            CentiToYocto,

            //milli enums
            MilliToYotta,
            MilliToZetta,
            MilliToExa,
            MilliToPeta,
            MilliToTera,
            MilliToGiga,
            MilliToMega,
            MilliToKilo,
            MilliToHecto,
            MilliToDeka,
            MilliToDeci,
            MilliToCenti,
            MilliToMilli,
            MilliToMicro,
            MilliToNano,
            MilliToPico,
            MilliToFemto,
            MilliToAtto,
            MilliToZepto,
            MilliToYocto,

            //micro enums
            MicroToYotta,
            MicroToZetta,
            MicroToExa,
            MicroToPeta,
            MicroToTera,
            MicroToGiga,
            MicroToMega,
            MicroToKilo,
            MicroToHecto,
            MicroToDeka,
            MicroToDeci,
            MicroToCenti,
            MicroToMilli,
            MicroToMicro,
            MicroToNano,
            MicroToPico,
            MicroToFemto,
            MicroToAtto,
            MicroToZepto,
            MicroToYocto,

            //nano enums
            NanoToYotta,
            NanoToZetta,
            NanoToExa,
            NanoToPeta,
            NanoToTera,
            NanoToGiga,
            NanoToMega,
            NanoToKilo,
            NanoToHecto,
            NanoToDeka,
            NanoToDeci,
            NanoToCenti,
            NanoToMilli,
            NanoToMicro,
            NanoToNano,
            NanoToPico,
            NanoToFemto,
            NanoToAtto,
            NanoToZepto,
            NanoToYocto,

            //pico enums
            PicoToYotta,
            PicoToZetta,
            PicoToExa,
            PicoToPeta,
            PicoToTera,
            PicoToGiga,
            PicoToMega,
            PicoToKilo,
            PicoToHecto,
            PicoToDeka,
            PicoToDeci,
            PicoToCenti,
            PicoToMilli,
            PicoToMicro,
            PicoToNano,
            PicoToPico,
            PicoToFemto,
            PicoToAtto,
            PicoToZepto,
            PicoToYocto,

            //femto enums
            FemtoToYotta,
            FemtoToZetta,
            FemtoToExa,
            FemtoToPeta,
            FemtoToTera,
            FemtoToGiga,
            FemtoToMega,
            FemtoToKilo,
            FemtoToHecto,
            FemtoToDeka,
            FemtoToDeci,
            FemtoToCenti,
            FemtoToMilli,
            FemtoToMicro,
            FemtoToNano,
            FemtoToPico,
            FemtoToFemto,
            FemtoToAtto,
            FemtoToZepto,
            FemtoToYocto,

            //atto enums
            AttoToYotta,
            AttoToZetta,
            AttoToExa,
            AttoToPeta,
            AttoToTera,
            AttoToGiga,
            AttoToMega,
            AttoToKilo,
            AttoToHecto,
            AttoToDeka,
            AttoToDeci,
            AttoToCenti,
            AttoToMilli,
            AttoToMicro,
            AttoToNano,
            AttoToPico,
            AttoToFemto,
            AttoToAtto,
            AttoToZepto,
            AttoToYocto,

            //zepto enums
            ZeptoToYotta,
            ZeptoToZetta,
            ZeptoToExa,
            ZeptoToPeta,
            ZeptoToTera,
            ZeptoToGiga,
            ZeptoToMega,
            ZeptoToKilo,
            ZeptoToHecto,
            ZeptoToDeka,
            ZeptoToDeci,
            ZeptoToCenti,
            ZeptoToMilli,
            ZeptoToMicro,
            ZeptoToNano,
            ZeptoToPico,
            ZeptoToFemto,
            ZeptoToAtto,
            ZeptoToZepto,
            ZeptoToYocto,

            //yocto enums
            YoctoToYotta,
            YoctoToZetta,
            YoctoToExa,
            YoctoToPeta,
            YoctoToTera,
            YoctoToGiga,
            YoctoToMega,
            YoctoToKilo,
            YoctoToHecto,
            YoctoToDeka,
            YoctoToDeci,
            YoctoToCenti,
            YoctoToMilli,
            YoctoToMicro,
            YoctoToNano,
            YoctoToPico,
            YoctoToFemto,
            YoctoToAtto,
            YoctoToZepto,
            YoctoToYocto
        }

        #endregion Prefix Dictionary

        #region Methods

        /// <summary>
        /// Gets the conversion factor for the specified prefix conversion.
        /// </summary>
        /// <param name="prefConv"></param>
        /// <returns></returns>
        public static double GetPrefixConversionFactor(PrefixConversion prefConv)
        {
            return _prefs[prefConv.ToString()];
        }

        #endregion Methods
    }
}
